Simplify logic for foreign __new__ and __call__: they do not accept keyword arguments
* So the error is now:
  TypeError: ForeignInstantiable.__call__() got an unexpected keyword argument 'kwarg'
  vs before:
  TypeError: invalid instantiation of foreign object

(cherry picked from commit 95b076038980628431dc08d661dc74e0b4bd5deb)